//import { Inter } from "next/font/google";
import Providers from "@/contexts/themeProvider";
import { Html, Head, Main, NextScript } from "next/document";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kars - Homepage",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Html lang="en">
      <Head />
      <body className="text-black bg-white">
        <Main />
        <NextScript />
        <Providers>{children}</Providers>
      </body>
    </Html>
  );
}

export default RootLayout;
